import { type InferPageType, loader } from "fumadocs-core/source";
import { changelog, pages } from "../../.source";
import { createMDXSource } from "fumadocs-mdx/runtime/next";
import { DEFAULT_LOCALE, LOCALES } from "@/i18n/routing";
import type { I18nConfig } from "fumadocs-core/i18n";

/**
 * Internationalization configuration for FumaDocs
 *
 * https://fumadocs.dev/docs/ui/internationalization
 */
export const docsI18nConfig: I18nConfig = {
  defaultLanguage: DEFAULT_LOCALE,
  languages: LOCALES,
  hideLocale: "default-locale",
};


/**
 * Turn a content source into a unified interface
 * .source folder is generated by `fumadocs-mdx`
 *
 * https://fumadocs.dev/docs/headless/source-api
 */

/**
 * Changelog source
 */
export const changelogSource = loader({
  baseUrl: "/changelog",
  i18n: docsI18nConfig,
  source: createMDXSource(changelog),
});

/**
 * Pages source
 *
 * TODO: how to set the baseUrl for pages?
 */
export const pagesSource = loader({
  baseUrl: "/pages",
  i18n: docsI18nConfig,
  source: createMDXSource(pages),
});

export type ChangelogType = InferPageType<typeof changelogSource>;
export type PagesType = InferPageType<typeof pagesSource>;

